language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

env:
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=1.11,<1.12"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django>=2.0,<2.1"

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort
  - npm install --save jslint -g
  - jslint --config ./.jslintrc ./django_netjsongraph/static/netjsongraph/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsongraph runtests.py

after_success:
  coveralls
