language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django>=1.9,<1.10"
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11,<1.12"

branches:
  only:
    - master

before_install:
  - pip install -r requirements-test.txt
  - ./runflake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./runisort; fi

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsongraph runtests.py

after_success:
  coveralls
